"""empty message

Revision ID: f0e2dcc7795e
Revises: 34f85fda55ec
Create Date: 2023-06-06 15:28:24.463201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e2dcc7795e'
down_revision = '34f85fda55ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('apellido_materno')
        batch_op.drop_column('apellido_paterno')

    # ### end Alembic commands ###
